### ISSUE TITLE
(Epic) Improve DevOps Processes (Part 1)

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#1034]
This DevOps Epic looks at our current processes and aims to improve them where possible:

Work items:

- [x] #1004 Smoke testing NPM packages
- [x] #1006 (Spike) Investigate performance analysis tools
- [x] #1007 Streamline Code Climate
- [x] #1094 Talk about release/tagging
- [x] #1105 (Spike) Optimise CI pipeline
- [x] #1127 Consolidate commit linting and checking fixups in CI pipeline 
- [x] #1132 Slack PR notifications
- [x] #1134 (Spike) Revisit DevOps principles to identify improvements
- [x] #1168 Refactor publish_next
- [x] #1172 Consolidate checkout/dependencies
- [x] #1207 Fix Code Climate PR comments 
- [x] #1209 Upgrade Lodash 
- [x] #1212 Add Create React App to NPM smoke test
- [x] #1229 (Spike) Install Storybook performance addon
- [x] #1265 (Spike) GitHub Actions migration plan
- [x] #1298 Migrate build & test feature to GHA
- [x] #1378 Add build design-tokens package job to GitHub actions build_and_test_feature workflow
