### ISSUE TITLE
(Epic) Timeline Enhancements (Part 1)

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#1205]
**Features:**
- [x] #1129 (Spike) Investigate Compound Timeline micro to macro view scaling
- [x] #1658 (Spike) Drag and drop
- [x]  #1537 Dev - Timeline Micro-to-macro view scaling

Precedes #1311 (Epic) Timeline Enhancements (Part 2)

**Comment by jk68mnpo** [comment]
From the list above (adding one), this is `Exemplar:RS` priority order:
1 - Hover or onClick for a timeline element to show a summary card
2 - View scaling (micro to macro / hours to years)
3 - Click to add events (onClick functionality on the whitespace in the timeline) 
4 - Infinite scroll
5 - Drag and Drop
6 - Copy and Paste

**Comment by el7h1rw2** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Q4 2020 Goals](https://trello.com/c/1Xs1c4FS/44-q4-2020-goals)
