### ISSUE TITLE
(Epic) Styled-Components Migration (establish patterns)

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#1206]
Introduction of styled components (needs architectural design, and work in migration).

- [x] #1170 (Spike) Investigate styled-components for React Component Library

- [x] #1331 Create and consume `@royalnavy/design-tokens` package
- [x] #951 Migrate Scheduler Framework styles from BEM to styled-components
