### ISSUE TITLE
(Epic) Improve DevOps Processes (Part 2)

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#1491]
This DevOps Epic looks at our current processes and aims to improve them where possible:

Work items:

- [x] #1443 (Spike) test semantic release with GitHub actions
- [x] #1551 Investigate & test new method for release automation
- [x] #1299  Migrate build test & deploy next to GHA
- [x] #1300 Migrate build test & deploy latest to GHA
