### ISSUE TITLE
(Epic) Forms v3 (Design)

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#1493]
Review the current form patterns, and update design system:

- [x] #1734 - Team feedback part 1
- [x] #1733 -  Team feedback part 2
- [x] #2008 - Edit forms part 1 to incorporate team feedback
- [ ] #2017 - Edit forms part 2 to incorporate team feedback
- [ ] #1735 - Visual design part 1
- [ ] #2018 - Visual design part 2
- [x] #1732 - Get public feedback
- [ ] #2022 -  Iterate forms part 1 to incorporate public feedback
- [ ] #2019 - Iterate forms part 2 to incorporate public feedback

**Comment by el7h1rw2** [comment]
Closes #977
