### ISSUE TITLE
Dev - Timeline Micro-to-macro view scaling

### ISSUE THREAD

**Issue by m7kvqbe1** [Royal-Navy/design-system#1537]
We've already done proof-of-concept work, with some assumptions being made. (Spike) Investigate Compound Timeline micro to macro view scaling #1129

Goal: Enable an 'out-of-the-box' solution to enable developers to change the scale.

**Acceptance Criteria:**

- [x] Define and prioritise design requirements based on customer needs
- [x] Define MVP scope
- [x] Provide visual design for MVP
- [x] Build as per visual design

**Tasks:**

- [x] Review proof-of-concept to understand scaling options
- [x] Interview customer teams to understand their implementation needs
- [x] Outline design requirements
- [x] Decide best plan to stage development (MVP and feature priorities)

**Comment by k9dh3zij** [comment]
MVP defined as follows:

- The controls will be a (+) and a (-) button (not a Slider)
- We'll add a small 'toolbar' right above the timeline
    - We'll move the (<) and (>) buttons into that toolbar
    - We'll introduce the (+) and (-) buttons in the toolbar, next to the (<) and (>) buttons

- No mouse zoom for MVP
- No transition effects for MVP
- Zoom in/out reference point is always the very left of the timeline
- Steps/resolution (baked-in for MVP - individual teams will not be able to change these):
    - Hour
    - Day quarter
    - Day
    - Week
    - Month
    - Year
    - 5-year
    
- Default to: Month

**Comment by k9dh3zij** [comment]
Designs to follow.

**Question:** Do we think doing the above could break anything downstream?

**Comment by k9dh3zij** [comment]
![Timeline toolbar](https://user-images.githubusercontent.com/73531035/107221052-053cfe80-6a0b-11eb-9a20-bb4d4b5267e9.png)

**Comment by k9dh3zij** [comment]
Ready for dev

**Comment by k9dh3zij** [comment]
[1537 - Timeline zoom.pdf](https://github.com/Royal-Navy/design-system/files/5990358/1537.-.Timeline.zoom.pdf)

@thyhjwb6  Visual adjustments for higher zoom levels

**Comment by thyhjwb6** [comment]
The work to move the navigation buttons is in [a separate ticket](https://github.com/Royal-Navy/design-system/issues/2016).

**Comment by k9dh3zij** [comment]
Agreed the following:

- For 5-year view, do not introduce separate year row yet. Instead, change 270° labels to 'JAN 2021', 'FEB 2021', ....

This keeps things within MVP scope and allows us to test, get feedback from end-users and consider a more holistic approach as part of the timeline re-design happening in Q2.

**Comment by thyhjwb6** [comment]
Work to update the month presentation for the 5 year view is in [a separate issue](https://github.com/Royal-Navy/design-system/issues/2042).
Work to update documentation is in [a separate ticket](https://github.com/Royal-Navy/design-system/issues/2041).
