### ISSUE TITLE
Initial iteration of `DatePickerE`

### ISSUE THREAD

**Issue by thyhjwb6** [Royal-Navy/design-system#2439]
[Design spec](https://docs.google.com/document/d/1MJlbdqhxQvt5qGn87Ubs2_OZUusdIgHwdV8NEofAMqQ/edit#heading=h.39kk8xu)

## Tasks 

- [x] Copy existing component
- [x] Remove deprecated features
- [x] Update styling of input
- [x] Update styling of calendar body
- [x] Add selection shading on hover for date ranges
- [x] Integrate with floating box component
- [x] Update styling and positioning of floating box
- [x] Update placeholder and automatic opening behaviour
- [x] Reopen on correct date
