### ISSUE TITLE
(Epic) Integrate headless CMS into existing site (1 of 3)

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#793]
Epic to link to all CMS work.
**Process steps:**
- Bake-off tests are written
- New CMS is 'Live'
- Docs site is migrated
- Docs site is forked into 'Service -Manual' and 'Platform-SDK'

**Work Items:**
- [x] #782 Create a list of actions for technical bake-off of Gatsby with headless CMS options
- [x] #784 Gatsby + Contentful technical analysis
- [x] #797 Gatsby + Prismic technical analysis
- [x] #827 (Spike) Investigate possibility of Storybook being able to export/expose add ons
- [ ] Re-run the bake-off tests, documenting vendor capabilities
- [ ] Integration work
