### ISSUE TITLE
(Epic) Create NELSON App

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#805]
- Create CRA template
- To also showcase API and container standards

https://github.com/facebook/create-react-app

**Work Items:**
- [x] #806 (Spike) Investigate CRA custom templates
- [x] #925 Review ESLint config, standardise for downstream consumers and expose
- [x] #808 Create CRA custom template

**Comment by el7h1rw2** [comment]
@m7kvqbe1 - Request from our sponsor to create a dummy app showcasing the design system, platform API and container standards.
