### ISSUE TITLE
(Epic) Design System infrastructure investigations and upgrades are delivered

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#811]
- AWS is ... ?
- Smoke tests are completed
- Branch deployments are ... ?

**Work Items:**

- [x] #814 (Spike) Branch deployments on AWS
- [x] #815 Document proposed design for AWS implementation
- [x] #816 (Spike) Smoke testing NPM package
- [x] #884 (Spike) Smoke testing NPM package part 2
