### ISSUE TITLE
(Epic) Technical Debt

### ISSUE THREAD

**Issue by el7h1rw2** [Royal-Navy/design-system#839]
Ongoing work to repay tech debt.

**Work Items:**
- [x] #865 Increase Dropdown test coverage
- [x] #864 Increase Pagination test coverage
- [x] #863 Increase PhaseBanner test coverage
- [x] #862 Increase Select test coverage
- [x] #861 Increase Switch test coverage
- [x] #818 Update the design system license file
- [x] #771 Remove use of uuid for component keys
- [x] #770 Remove data-testid from component HTML output
- [x] #759 Form State Refactor
- [x] ~~#744 Remove generate-exports.sh from icon-library~~
- [ ] #645 The method used to raise events on components is inconsistent
- [x] #592 Introduce more constants
- [x] #390 Component CSS tweaks to match Sketch file
